### PR TITLE
Upgrading Openshift Jenkins Plugin to use DSL version

### PR DESCRIPTION
**Pull request by myeung18**
Signed-off-by: Marco Yeung <myeung@redhat.com>

Old version will no longer be supported after OpenShift 3.11.

### CODE REVIEW

**Review by bmozaffa — CHANGES_REQUESTED** [review]
@myeung18 Please rebase to reconcile changes in the last 2 PRs that were merged.

**Review by redhatHameed — COMMENTED** [review]
it looks Marco re-merge my changes again, the same file showing to me for review which I committed in my PR, I verified to make sure that all files are there .

**Comment by bmozaffa** [comment]
Hmm, @myeung18 , do you still have your commits separately on your machine? We should try to fix this.

**Comment by myeung18** [comment]
> Hmm, @myeung18 , do you still have your commits separately on your machine? We should try to fix this.

I rebased the RHsyseng's master to openshiftpluginupgrade branch.  It now has all the changes.   No more local or other commits.

**Pull request closed without merging**
