### PR TITLE
added 3scale toolbox Jenkins pipelines to publish API on 3scale and improvements in readme files

### PR DESCRIPTION
**Pull request by redhatHameed**
[WIP] added 3scale toolbox Jenkins pipeline to publish API on 3scale and improvements in readme files

Signed-off-by: Abdul Hameed <ahameed@redhat.com>

### CODE REVIEW

**Review by bmozaffa — COMMENTED** [review]
Good stuff! I will only note that there is a substantial amount of whitespace changes, much of it likely the result of an IDE/code formatter, that makes it hard to review the changes. One solution is to first do a global code format in one commit, and the actual changes in a second commit of the same PR, to avoid this problem.

**Comment by redhatHameed** [comment]
> Good stuff! I will only note that there is a substantial amount of whitespace changes, much of it likely the result of an IDE/code formatter, that makes it hard to review the changes. One solution is to first do a global code format in one commit, and the actual changes in a second commit of the same PR, to avoid this problem.

@bmozaffa yup these happen in result with code formatter - you can ignore them by going in
 "Diff settings", "Hide whitespace changes", and then "Apply and reload".
diff
Let me if this something will work

**Comment by nmasse-itix** [comment]
This PR will fix #18

**Comment by redhatHameed** [comment]
@nmasse-itix added application plans with pricing rules import from artifact file, Please review when you have time and merge it if it looks good.

**Comment by nmasse-itix** [comment]
Very good @redhatHameed ! 👍Let's merge this !

**Pull request merged**
